name: dataproc-env

channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter=1.0
  - notebook=6.5
  - numpy=1.23
  - astropy=5.2
  - ccdproc=2.4
  - matplotlib=3.6
  - astroquery=0.4
  - photutils=1.6
  - pandas=1.5
  - scipy=1.9
  - scikit-learn=1.2
  - dask=2022
