name: dataproc-env

channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter=1.0
  - notebook=6.5
  - numpy=1.25
  - astropy=6.1
  - ccdproc=2.4
  - matplotlib=3.8
  - astroquery=0.4
  - photutils=1.11
  - pandas=1.5
  - scipy=1.9
  - scikit-learn=1.2
